version: 2
jobs:
  build:
    docker:
      - image: tozd/meteor-testing:ubuntu-xenial
    environment:
      - METEOR_ALLOW_SUPERUSER: true
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: tests/authors/check-authors.sh
      - run:
          command: |
            # No merge marks in commits.
            ! git log --oneline "-G^(<<<<<<<|=======|>>>>>>>)" | grep '^'
      - run: meteor npm install --unsafe-perm selenium-webdriver@2.47.0 mkdirp
      - run: meteor npm install --unsafe-perm -g cli-real-favicon
      - run: meteor npm install --unsafe-perm
      - run: tests/test-runner/test-all.sh
      - run: real-favicon check-for-update --fail-on-update public/version.json
      - store_test_results:
          path: test-reports/
